version: "3.7"
services:
  mongo:
    image: mongo:latest
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db    
  ludum-materiais:
    image: guilhermesiqueira/ludum-materiais
    ports:
      - "8081:8081"
    links:
      - mongo